### ISSUE TITLE
Just saying hi

### ISSUE THREAD

**Issue by morrownr** [radxa/rtl8852bu#1]
Just happened to run across this. I hope this driver is better than v1.15.0.1 for the 8852au.

I run the below site. It includes 5 Realtek drivers. I was hoping to make the 8852au driver available to the public and just could not get it anywhere near close to something that would be reasonable so I just stopped work and posted a review recommending Linux users stay away from adapters based on the 8852au and 8832au.

https://github.com/morrownr/USB-WiFi

If you are thinking about buying 8852xu or 8832xu based adapters, use caution and be aware that Mediatek will be releasing USB WiFi 6 chipsets soon. In fact the driver is already in-kernel as of 5.18.

Regards

**Comment by RadxaYuntian** [comment]
My understanding is that this driver is for 8852bu only. For example there is no 8852a or 8852c folder in https://github.com/radxa/rtl8852bu/tree/main/phl/hal_g6/

**Comment by alkisg** [comment]
Hi guys,

@morrownr thank you for your rtl 88xx drivers, you've been doing an awesome work with them!
I got an 8852bu-based adapter and I tested it with [this 8852bu 1.15.11-36 driver version](https://drive.google.com/file/d/1r-cDn3Ou5y16juWpjXpeGfG6XCI-GLJj/view?usp=share_link), released on 12 Sep 2022.
It seemed stable and pretty fast to me, I guess the driver matured from the earlier 15.1 version.
I tested it and it worked fine on 10 different versions of Debian and Ubuntu (x86_64/x86_32, from 2012 and on),
and on both the armhf and arm64 versions of Rasperry Pi OS Bullseye.
On Ubuntu 22.04 Raspberry Pi edition, I saw a glitch where it stopped downloading after 1 GB; with rmmod/modprobe it continued and successfully downloaded another 50 GB with no other issues.

Unfortunately it only supports kernels up to 5.17, so I can use it with e.g. Ubuntu 22.04 but not with Ubuntu 22.10.

@RadxaYuntian feel free to update this repository with the more recent version that I linked, if you wish.

Cheers,
Alkis

**Comment by RadxaYuntian** [comment]
Thanks for the offering. However, this repo is meant to be tracking whatever our vendor provides us, so we can get support from them when issue arises. As such I cannot accept code from non official channel.

I'll also close this issue since the original concern was handled already.

**Comment by alkisg** [comment]
Oh, I didn't realize vendors ship different versions of the Realtek code, I thought everyone had the same GPLv2-based freely redistributable code, just different snapshots of it depending on the release date. Sorry for the offtopic then!

**Comment by morrownr** [comment]
@alkisg 

If you are interested in working with me to see what can be done with the Sep version of the driver, please go to:

https://github.com/morrownr/USB-WiFi

...then post a new issue in that repo that is basically the same as your first message here (above). That will let me know you are interested in working with me. I already have a local repo with the new driver. It can be made into a private github repo in a couple of minutes and then I could give you access. That way we can communicate.

> Unfortunately it only supports kernels up to 5.17

Most likely I can fix that. The public Realtek drivers I have up were only supported to kernel 5.11 by Realtek but they all support kernels up to and including kernel 6.1 now.

Nick
