### ISSUE TITLE
Compiling rtl8852bu

### ISSUE THREAD

**Issue by nowhiskey** [radxa/rtl8852bu#2]
Hello, i am having troubles with ma realtek wifi and bluetooth. The Machine is a Thinkpad e15 gen4. i just compiled the kernel 5.18 to see if it works better. And indeed, now i am getting this info:

root@Murija9:/home/afadoc# dmesg |grep firmware
[    0.061103] Spectre V2 : Enabling Restricted Speculation for firmware calls
[    3.667876] [drm] Loading DMUB firmware via PSP: version=0x01010019
[    3.668465] [drm] Found VCN firmware Version ENC: 1.14 DEC: 5 VEP: 0 Revision: 20
[    3.668469] amdgpu 0000:04:00.0: amdgpu: Will use PSP to load VCN firmware
[    3.853478] psmouse serio1: elantech: assuming hardware version 4 (with firmware version 0x5f3001)
[    6.924768] bluetooth hci0: Direct firmware load for rtl_bt/rtl8852bu_fw.bin failed with error -2
[    6.924771] Bluetooth: hci0: RTL: firmware file rtl_bt/rtl8852bu_fw.bin not found

Than searching for the 8852bu i found your repository.

I did:

git clone https://github.com/radxa/rtl8852bu.git

But when running make, i get this error:

afadoc@Murija9:~/Schreibtisch/install/rtl8852bu$ make
#rm -f .symvers.8852bu
make ARCH= CROSS_COMPILE= -C  M=/home/afadoc/Schreibtisch/install/rtl8852bu  modules
make[1]: *** M=/home/afadoc/Schreibtisch/install/rtl8852bu: Datei oder Verzeichnis nicht gefunden.  Schluss.
make: *** [Makefile:633: modules] Fehler 2

I am not sure why this happens, but anyway - if you have any advice what i could do, i would be really thankfull.

Thank you!

Dragan

**Comment by RadxaYuntian** [comment]
Hi Dragan. We uploaded the source code as-is from vendor, and only made necessary modifications to allow it to build along with Linux kernel. This is because we only need to ship the driver as part of the device specific kernel packages, so an out-of-tree build is not validated. As such we cannot answer your question.

If you are interested in an in-tree build instead, you can make similar modification to your kernel like [this patch](https://github.com/radxa-repo/lbuild/blob/main/forks/rockchip-5.10/rock-5a/0002-VENDOR-wireless-Add-RTL8852BU-driver.patch) (targeting vendor kernel so not applicable on mainline 5.18), and revert the platform change [here](https://github.com/radxa/rtl8852bu/commit/cf2fadc644c9a5c5ded0df1da87d2a1790ba11ce).

**Comment by RadxaYuntian** [comment]
Also your dmesg seems to indicate Bluetooth issue. This repo is only the Wi-Fi part of 8852BU, and the bluetooth driver is located at [here](https://github.com/radxa/rtkbt). We haven't got the latter to work on our device though.

**Comment by nowhiskey** [comment]
Hello, thanks for the answer.

I my case i am looking for both - wifi and bluetooth, since they both are not working here:

afadoc@Murija9:~/Schreibtisch$ lsusb 
Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 003 Device 003: ID 0bda:4853 Realtek Semiconductor Corp. Bluetooth Radio

afadoc@Murija9:~/Schreibtisch$ sudo lspci 
03:00.0 Network controller: Realtek Semiconductor Co., Ltd. Device b852

With the new kernel at least 'dmesg' is showing the bluetooth is trying to load the firmware:

afadoc@Murija9:~/Schreibtisch$ sudo dmesg |grep firm
[    5.730737] bluetooth hci0: Direct firmware load for rtl_bt/rtl8852bu_fw.bin failed with error -2
[    5.730740] Bluetooth: hci0: RTL: firmware file rtl_bt/rtl8852bu_fw.bin not found
afadoc@Murija9:~/Schreibtisch$ 


Cheers,

Dragan

**Comment by RadxaYuntian** [comment]
Try put mentioned files from [here](https://github.com/radxa/rtkbt/tree/main/rtkbt-firmware/lib/firmware) to `/lib/firmware/rtl_bt` and see if that helps. If not you will have to see if you can build the driver yourself.

**Comment by nowhiskey** [comment]
Hello, thank you so much - this seems to work so far!

Bluetooth device is up and running. I am able to pair with other devices here.

Only i cannot get the sound (it's pulseaudio running on debian11) to play through the device:

afadoc@Murija9:~$ pactl load-module module-bluetooth-discover
Fehlgeschlagen: Entität nicht vorhanden

It want load the module . I am investigating right now why this is happening.

Thank you a lot!

Dragan

**Comment by nowhiskey** [comment]
Hello, i wanted to report that it works now. Sometimes my HiFi device is shown in the blueman-applet as if it is not an sound devise, but this is some bluez bug. 'sudo dpkg-reconifgure bluez'  helps in that case.

I'd like to thank you one more time - really appreciated your help!

Dragan

**Comment by RadxaYuntian** [comment]
Glad you got it working. Do you mind sharing what exactly you did to enable Bluetooth though? We are having the same issue where we can pair with devices but they are not properly communicating.

**Comment by nowhiskey** [comment]
Hello,i am usingDebian 11 testing5.18 kernel self compiledpulseaudiopavucontrolbluezblueman-appletxfce4Don't know the versions, not on that machine right now.Copied your files into the right placebluetooth is started at boot timeconnect with the audio device (at this moment no ports are displayed in the pavucontrol)now do:sudo dpkg-reconfigure bluezbluetooth is restarted and the audio device disconnectedNow stop Bluetooth with the blueman-appletAgain start the Bluetooth with the blueman-appletNow connect the audio device againDevice is shown correctly with the output ports in the pavucontrol.Tried several times and it works now.I hope that this info helps you in some way.Have a good day,Dragan Am 31.05.2022, 03:42 schrieb Yuntian Zhang ***@***.***>:

   
  Glad you got it working. Do you mind sharing what exactly you did to enable Bluetooth though? We are having the same issue where we can pair with devices but they are not properly communicating.
